name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu20.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get install build-essential libtool bsdmainutils autotools-dev autoconf pkg-config automake python3 libssl-dev libgmp-dev libevent-dev libboost-all-dev libsodium-dev cargo libdb-dev libdb++-dev 
      
    - name: configure
      run: ./autogen.sh && ./configure --with-incompatible-bdb

    - name: Make
      run: make clean && make

